# ブランチは手動、testというパラメータを受け取って、それを出力する
name: test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Show branch name
        run: echo ${{ github.event.inputs.branch }}
