# ブランチは手動、testというパラメータを受け取って、それを出力する
name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch name
        id: branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"
      - name: Show branch name
        run: echo ${{ steps.branch.outputs.branch }}
